### ISSUE TITLE
can link sharing be added?

### ISSUE THREAD

**Issue by nixoye** [JustSch/node-snapdrop-electron#3]
It would be very convenient if we could easily share a link to a device as well.

**Comment by JustSch** [comment]
do you mean linking to the device itself or being able to send a link? You can send a link itself by copy pasting it into the send a message that pops up when right clicking the name of the device you want to send it to or pressing and holding the device name on mobile

**Comment by nixoye** [comment]
Ah yeah i mesnt sending a link. I didnt know we could right click to send a message. perfect, thanks!
