### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by LisaJackson24-2** [JustSch/node-snapdrop-electron#35]
Everything works, thank you very much.

But there are several remarks on the work itself. It is especially annoying that the application window does not retain its size and position after restarting. Also, you cannot specify a default file storage location. Another unpleasant thing is that at the address 192.168.56.1:3001 it is impossible to find devices in one network, but if you open another window in the browser, it finds each other. But this is only on one computer. Everything works multiple devices fine with the address 192.168.0.2:3001. That's why it would be great have the opportunity if you could choose and change the access address that is displayed when you start the application, so that if you need to manually enter the address, you don't have to scroll through all address variant. Probably the best option is just to be able to just save the settings.

And in general, the most ideal option would be if you still created just .exe and .dmg files to start the node server itself, without the electron application. To simply start the server, without the command line, manual installation of dependencies, etc. Something like how VLC Remote implements it. Then you can simply add the start of the server to autoboot with the system, and work with the service through the browser.

**Comment by JustSch** [comment]
It does sometimes get the wrong ip address if you have more than one network adapter. In my own case it gets the network adapter used by my vpn or vm's. This is why I have the "Can't Connect? Click here for other network adapter ip addresses." I do eventually want to have it check which one it can actually use to connect and display that one first and I'll probably look into it when i have some time.

The original purpose of this fork was to wrap the original snapdrop app in an electron app so i could use it when the server was down but I may look into a backend only solution (no electron) since you'd still be able to access it from the browser 🤔

**Comment by JustSch** [comment]
I have now set up a way to run the backend only (no electron) by running "node backendOnly.js" and you can set the ip with "node backendOnly.js {PUT IP ADDRESS HERE}" without brackets. This still with commandline but for now you can set it to start at boot using something like (nssm)[https://nssm.cc/]. Idk of a macos solution as I don't have a mac

**Comment by LisaJackson24-2** [comment]
> It does sometimes get the wrong ip address if you have more than one network adapter. In my own case it gets the network adapter used by my vpn or vm's. This is why I have the "Can't Connect? Click here for other network adapter ip addresses." I do eventually want to have it check which one it can actually use to connect and display that one first and I'll probably look into it when i have some time.
> 
> The original purpose of this fork was to wrap the original snapdrop app in an electron app so i could use it when the server was down but I may look into a backend only solution (no electron) since you'd still be able to access it from the browser 🤔

Ok, I understand about the IP 🤪

It would be great if you could actually make a non-electron variant, it shouldn't be difficult given your current variant. Because electron is quite capricious, and in general, the application is less convenient from the server's point of view. It will not be able to auto run with the system so that it does not interfere. But  just an exe/dmg that will start a server in the background, it's really convenient, especially if you use several devices and need to transfer from phone to phone, because it is not at all convenient to manually launch the application on your computer for this.

Therefore, I will wait for you to really think about implementing it 😉

**Comment by LisaJackson24-2** [comment]
> I have now set up a way to run the backend only (no electron) by running "node backendOnly.js" and you can set the ip with "node backendOnly.js {PUT IP ADDRESS HERE}" without brackets. This still with commandline but for now you can set it to start at boot using something like [nssm](https://nssm.cc/) . Idk of a macos solution as I don't have a mac

Well, to put it mildly, it is not convenient at all.

**Comment by JustSch** [comment]
> > I have now set up a way to run the backend only (no electron) by running "node backendOnly.js" and you can set the ip with "node backendOnly.js {PUT IP ADDRESS HERE}" without brackets. This still with commandline but for now you can set it to start at boot using something like [nssm](https://nssm.cc/) . Idk of a macos solution as I don't have a mac
> 
> Well, to put it mildly, it is not convenient at all.

I did write "for now" as these are the initial steps towards an easier solution but it is something that works right now

**Comment by JustSch** [comment]
this is outside the scope of this project as it was originally meant to wrap the nodejs version of snapdrop in an electron app and other projects such as [landrop](https://landrop.app/) would serve this need better
