### ISSUE TITLE
.exe and .dmg server

### ISSUE THREAD

**Issue by LisaJackson24-2** [JustSch/node-snapdrop-electron#36]
Could you implement the server in the form of .exe and .dmg files, as for example done in VLC Remote? This will allow simple beginners to use this wonderful service without unnecessary difficulties, simply by adding them to the system startup. I will be very grateful 🙏

**Comment by JustSch** [comment]
I might look into an exe but I would like to use a platform agnostic approach such as using something like nssm to just run the node server. Since i dont have a mac idk how i would build a .app (.dmg is a disc image usually used by mac installers) unless I can find a way to do it with github actions like i do for the electron build

**Comment by LisaJackson24-2** [comment]
> I might look into an exe but I would like to use a platform agnostic approach such as using something like nssm to just run the node server. Since i dont have a mac idk how i would build a .app (.dmg is a disc image usually used by mac installers) unless I can find a way to do it with github actions like i do for the electron build

The ideal implementation in my opinion is something like VLC Remote. dmg is a disk image, but you can simply unpack it into folders, and create a shortcut to start the server in the launcher. And the IP will be find out with the tools of the system itself. IP will not change, so it will only have to be done once.

Well, now you have separate packages for the OS, so all I want is for the program to run in the background when you click on the shortcut, but without Electron, it won't be noticeable to the user, will be just a launched process in the task manager. That's all.

**Comment by JustSch** [comment]
currently this is outside the scope of this fork as you need the local ip address to connect to it from other devices and I use the electron window to give it (even if the initial ip address it gives cannot always be used if you have multiple network adapters). You can just leave the electron window minimized so it runs in the background and even connect to it from another browser on the same pc running it to avoid using the electron window. Although, the electron window will always appear as a client. You may be better served by [landrop](https://landrop.app/) which does run in the background and has a tray icon on windows as well as gives the names of the devices so you don't have to worry about the ip addresses
